# https://taskfile.dev

version: '3'

includes:
  docs: ./.github/taskfiles/docs.yml
  chart: ./.github/taskfiles/chart.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:
    desc: setup environment
    cmds:
      - brew install helm helm-docs

  docs:
    summary: Documentation specific tasks.
    cmds:
      - task: docs:default
      #- for chart in charts/*; do cp $chart/README.md docs/$chart.md; done
      #- cp -f .cr-index/index.yaml docs/index.yaml || curl https://{{.PROD_DOMAIN}}/index.yaml --output docs/index.yaml
