apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: peertube
  name: peertube
spec:
  ports:
    - name: "1935"
      port: 1935
      targetPort: 1935
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: peertube
