apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.server.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{- .Values.name }}
  namespace: {{- .Values.namespace }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  replicas: {{ .Values.peertube.replicas }}
  selector:
    matchLabels:
      {{- include "argo-cd.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 6 }}
  {{- with include "argo-cd.strategy" (mergeOverwrite (deepCopy .Values.global.deploymentStrategy) .Values.server.deploymentStrategy) }}
  strategy:
    {{- trim . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.server.podAnnotations) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.server.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{- .Values.peertube.name }}
          image: {{- .Values.image }}
          ports:
            - containerPort: 1935
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          env:
            - name: PEERTUBE_CONTACT_FORM_ENABLED
              value: "false"
            - name: PEERTUBE_DB_HOSTNAME
              value: postgres
            - name: PEERTUBE_DB_PASSWORD
            - name: PEERTUBE_DB_SSL
              value: "false"
            - name: PEERTUBE_DB_USERNAME
              value: peertube
            - name: PEERTUBE_SIGNUP_ENABLED
              value: "false"
            - name: PEERTUBE_TRANSCODING_ENABLED
              value: "true"
            - name: PEERTUBE_WEBSERVER_HOSTNAME
              value: '{{- .Values.subdomain }}.{{- .Values.base_domain }}'
            - name: POSTGRES_DB
              value: peertube
          volumeMounts:
            - mountPath: /app/client/dist
              name: assets
            - mountPath: /data
              name: data-peertube
            - mountPath: /config
              name: config-peertube
      restartPolicy: Always
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: assets
        - name: data-peertube
          persistentVolumeClaim:
            claimName: data-peertube
        - name: config-peertube
          configMap: 
            name: '{{ .Release.Name }}-configmap'
            items:
              - key: 'helm-config.yaml'
                path: 'helm-config.yaml'
