apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.peertube.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key  | nindent 4 }}: {{ $value }}
    {{- end }}
  {{- end }}
  name: '{{ .Values.name }}'
  namespace: '{{ .Values.namespace }}'
spec:
  replicas: {{ .Values.peertube.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: peertube
  template:
    metadata:
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.peertube.podAnnotations) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key | nindent 8 }}: {{ $value }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: '{{ .Values.peertube.name }}'
          image: '{{ .Values.peertube.image.repository }}:{{ .Values.peertube.image.image }}'
          ports:
            - containerPort: 1935
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          env:
            - name: PEERTUBE_CONTACT_FORM_ENABLED
              value: "false"
            - name: PEERTUBE_DB_HOSTNAME
              value: postgres
            - name: PEERTUBE_DB_PASSWORD
            - name: PEERTUBE_DB_SSL
              value: "false"
            - name: PEERTUBE_DB_USERNAME
              value: peertube
            - name: PEERTUBE_SIGNUP_ENABLED
              value: "false"
            - name: PEERTUBE_TRANSCODING_ENABLED
              value: "true"
            - name: PEERTUBE_WEBSERVER_HOSTNAME
              value: '{{- .Values.subdomain }}.{{- .Values.base_domain }}'
            - name: POSTGRES_DB
              value: peertube
          volumeMounts:
            - mountPath: /app/client/dist
              name: assets
            - mountPath: /data
              name: data-peertube
            - mountPath: /config
              name: config-peertube
      restartPolicy: Always
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: assets
        - name: data-peertube
          persistentVolumeClaim:
            claimName: data-peertube
        - name: config-peertube
          configMap: 
            name: '{{ .Release.Name }}-configmap'
            items:
              - key: 'helm-config.yaml'
                path: 'helm-config.yaml'
