apiVersion: v1
kind: Secret
metadata:
    labels:
        io.kompose.service: peertube
    name: "{{ .Release.Name }}-configmap"
type: 
data:
    helm-config.yaml: |-
{{ .Files.Get "configmap/helm-config.yaml" | nindent 4 }}

