apiVersion: v2
name: peertube
version: 0.0.1
appVersion: v6.3.2-bookworm
kubeVersion: ">=1.25.0-0"
description: A Helm Chart for chocobozzz/peertube, a self-hosted federated video publishing platform
keywords:
  - peertube
home: https://github.com/ice-bergtech/ice-helm
sources:
  - https://github.com/ice-bergtech/helm-charts/tree/main/charts/peertube
  - https://github.com/Chocobozzz/PeerTube
  - https://hub.docker.com/r/chocobozzz/peertube/tags
maintainers:
  - name: Iceberg Tech
    url: https://ice-bergtech.github.io/
# dependencies:
#   - name: redis-ha
#     version: 4.27.6
#     repository: https://dandydeveloper.github.io/charts/
#     condition: redis-ha.enabled
