## Peertube configuration
## Ref: https://github.com/ice-bergtech/helm-charts
## Ref: https://github.com/Chocobozzz/PeerTube

# -- Provide a name in place of `Peertube`
name: 'Peertube'

image: 'v6.3.2-bookworm' 

# -- Override the namespace
# @default -- `.Release.Namespace`
namespaceOverride: ""
# Override APIVersions
# If you want to template helm charts but cannot access k8s API server
# you can set api versions here
apiVersionOverrides: {}

redis-ha.enabled: false

hostname: 'peertube.local'



## Peertube Configs
## Ref: https://github.com/Chocobozzz/PeerTube/blob/develop/config/production.yaml.example
peertube:
  # Instance Configuration
  instance:
    # -- Short description of server
    short_description: ''
    # -- Long Description of server
    description: ''
    # -- If server is NSFW
    is_nsfw: false
    # -- NSFW default policy
    default_nsfw_policy: do_not_list
    # -- Legal Terms
    terms: 'No terms for now.'
    # -- Code of Conduct
    code_of_conduct: ''
    # -- Reason for server creation
    creation_reason: ''
    # -- Information about moderation policies
    moderation_information: ''
    # -- Primary administrator
    administrator: ''
    # -- Log of instance maintenance
    maintenance_lifetime: ''
    # -- Instance business model
    business_model: ''
    # -- Instance hardware info
    hardware_information: ''
    # -- Video Categories
    categories: []
    languages: []
    # -- Default client route
    default_client_route: "/videos/trending"
    # -- Default instance theme
    default_theme: 'dark'
  # Service Links
  services: |
    # Cards configuration to format video in Twitter/X
    # All other social media (Facebook, Mastodon, etc.) are supported out of the box
    twitter:
      # Indicates the Twitter/X account for the website or platform where the content was published
      # This is just an information injected in HTML that is required by Twitter/X
      username: '@Chocobozzz'
  # -- Cache Settings
  cache: |
    previews:
      size: 50
    captions:
      size: 50
    torrents:
      size: 50
  # Signup settings
  signup: |
    enabled: false
    limit: 10
    requires_email_verification: false
    minimum_age: 16
  # Import Settings
  import: |
    videos:
      concurrency: 1
      http:
        enabled: false
      torrent:
        enabled: false
    video_channel_synchronization:
      enabled: false
  trending:
    videos:
      algorithms:
        enabled:
        - hot
        - most-viewed
        - most-liked
        default: most-viewed
  admin.email: ''
  contact_form.enabled: false
  user:
    video_quota: -1
    video_quota_daily: -1
    max_channels: 20
  # -- Transcoding settings 
  transcoding: |
    enabled: true
    threads: 1
    allow_additional_extensions: true
    allow_audio_files: true
    profile: default
    concurrency: 1
    resolutions:
      0p: false
      144p: false
      240p: false
      360p: false
      480p: false
      720p: false
      1080p: false
      1440p: false
      2160p: false
    always_transcode_original_resolution: true
    hls:
      enabled: true
    webtorrent:
      enabled: false
  followers: |
    instance:
      # Allow or not other instances to follow yours
      enabled: true
      # Whether or not an administrator must manually validate a new follower
      manual_approval: false
  followings: |
    instance:
      # If you want to automatically follow back new instance followers
      # If this option is enabled, use the mute feature instead of deleting followings
      # /!\ Don't enable this if you don't have a reactive moderation team /!\
      auto_follow_back:
        enabled: false

      # If you want to automatically follow instances of the public index
      # If this option is enabled, use the mute feature instead of deleting followings
      # /!\ Don't enable this if you don't have a reactive moderation team /!\
      auto_follow_index:
        enabled: false
        # Host your own using https://framagit.org/framasoft/peertube/instances-peertube#peertube-auto-follow
        index_url: ''
  broadcast_message: |
    enabled: false
    level: info # 'info' | 'warning' | 'error'
    message: '' # Supports markdown
    dismissable: false
  # -- Search configuration
  search: |
    # Add ability to fetch remote videos/actors by their URI, that may not be federated with your instance
    # If enabled, the associated group will be able to "escape" from the instance follows
    # That means they will be able to follow channels, watch videos, list videos of non followed instances
    remote_uri:
      users: true
      anonymous: false

    # Use a third party index instead of your local index, only for search results
    # Useful to discover content outside of your instance
    # If you enable search_index, you must enable remote_uri search for users
    # If you do not enable remote_uri search for anonymous user, your instance will redirect the user on the origin instance
    # instead of loading the video locally
    search_index:
      enabled: false
      # URL of the search index, that should use the same search API and routes
      # than PeerTube: https://docs.joinpeertube.org/api-rest-reference.html
      # You should deploy your own with https://framagit.org/framasoft/peertube/search-index,
      # and can use https://search.joinpeertube.org/ for tests, but keep in mind the latter is an unmoderated search index
      url: ''
      # You can disable local search in the client, so users only use the search index
      disable_local_search: false
      # If you did not disable local search in the client, you can decide to use the search index by default
      is_default_search: false
  secrets:
    peertube: ''
